### PR TITLE
Add \XBase\Record::getData

### PR DESCRIPTION
**Pull request by s-chizhik**
Hi! Thx for your lib.

I'd like to propose adding `\XBase\Record::getData`, to get all `\XBase\Record` fields in one touch.

Also, would you consider to tag latest master changes with or without this PR?

### CODE REVIEW

**Comment by gam6itko** [comment]
Could you provide a description for this method and `choppedData` property please?

**Comment by s-chizhik** [comment]
@gam6itko yes, sure.

I suppose, `choppedData` using to store raw data, which was fetched from certain database row. This method will help to get this data in one call.

To make this method name more consistent, I can rename it to `getChoppedData`, and method `getData` refactor so it will return data based on each column type.

**Comment by gam6itko** [comment]
@s-chizhik There is not enough description in the project. Since you figured out how it works and made edits, I ask you to add a description to help other developers to improve the product. Method name is fine

**Comment by s-chizhik** [comment]
@gam6itko oh, I see that you talking about a comment in code :)

Also, in your opinion, do we need different methods to get raw values and typed values?

It will looks like:
```PHP
    public function getChoppedData() {
       // ...
    }

    public function getData()
    {
        $fields = array();

        foreach ($this->getColumns() as $column) {
            $fields[$column->name] = $this->getObject($column);
        }

        return $fields;
    }
```

**Comment by gam6itko** [comment]
It will be nice

**Comment by s-chizhik** [comment]
Are new changes fine?

**Comment by gam6itko** [comment]
@s-chizhik thanks, comrade

**Comment by s-chizhik** [comment]
@gam6itko thx a lot 👍

**Pull request merged**
