### PR TITLE
Include high-order byte in field length calculation for non-numeric fields

### PR DESCRIPTION
**Pull request by jlindsey3**
This is what I have to do to get correct memo field lengths on a bunch of DBF files that I have to read in. Throwing it out there for consideration.

See #7 at http://www.manmrk.net/tutorials/database/xbase/dbf.html#DBF_NOTE_7_SOURCE

### CODE REVIEW

**Comment by gam6itko** [comment]
@jlindsey3 Thanks for PR. Actually I don't have any case to test your improvement. Can you provide dbf file for tests?

**Comment by jlindsey3** [comment]
Thanks @gam6itko 

No problem, here is a DBF and FPT

https://github.com/DMSWorksLLC/php-xbase-test-data

**Comment by gam6itko** [comment]
Testing the library with your file showed no errors. Do you have a problem with this file and php-xbase library?

**Comment by jlindsey3** [comment]
So sorry, I accidentally gave you the wrong file. I have pushed the correct one, F5_2.DBF, which has 18 fields and 5 rows. This file does not parse correctly with php-xbase because the field "note" (type C) has a length of 300 but php-xbase thinks it is only 44 because it does not consider the high byte. This throws off the offsets for all fields following "note," and the result is that none of the memo fields following it are correctly read in.

I don't know if having fields longer than 255 is standard, but my actual data files definitely do have several C fields with long lengths.

Thanks for your time, I hope this helps!

**Comment by gam6itko** [comment]
@jlindsey3 ok I've found the moment you're talking about. Thanks for your contribution

**Pull request merged**
